export type JobCategory =
  | 'tech'
  | 'finance'
  | 'healthcare'
  | 'consulting'
  | 'nonprofit'
  | 'startup'
  | 'enterprise';

export type JobType = 'Full-time' | 'Part-time' | 'Contract';
export type WorkMode = 'Remote' | 'Hybrid' | 'On-site';

export interface ChiefOfStaffJob {
  id: string;
  title: string;
  company: string;
  heroImage: string;
  heroImageAlt: string;
  location: string;
  country: string;
  workMode: WorkMode;
  type: JobType;
  salary: string;
  description: string;
  requirements?: string;
  skills: string[];
  postedDate: string;
  validThrough?: string;
  externalUrl: string;
  source: 'greenhouse' | 'linkedin' | 'company-site' | 'job-board';
  category: JobCategory;
  executiveType: 'CEO' | 'COO' | 'CFO' | 'Founder' | 'Managing Partner' | 'President' | 'Division Head';
  companyStage: 'Seed' | 'Series A' | 'Series B' | 'Series C+' | 'Growth' | 'Enterprise' | 'Public';
}

export const categoryLabels: Record<JobCategory, string> = {
  tech: 'Technology',
  finance: 'Finance & Banking',
  healthcare: 'Healthcare',
  consulting: 'Consulting',
  nonprofit: 'Nonprofit & Government',
  startup: 'Startup',
  enterprise: 'Enterprise',
};

export const categoryColors: Record<JobCategory, { bg: string; border: string; text: string }> = {
  tech: { bg: 'bg-blue-500/10', border: 'border-blue-500/30', text: 'text-blue-400' },
  finance: { bg: 'bg-green-500/10', border: 'border-green-500/30', text: 'text-green-400' },
  healthcare: { bg: 'bg-red-500/10', border: 'border-red-500/30', text: 'text-red-400' },
  consulting: { bg: 'bg-purple-500/10', border: 'border-purple-500/30', text: 'text-purple-400' },
  nonprofit: { bg: 'bg-teal-500/10', border: 'border-teal-500/30', text: 'text-teal-400' },
  startup: { bg: 'bg-orange-500/10', border: 'border-orange-500/30', text: 'text-orange-400' },
  enterprise: { bg: 'bg-indigo-500/10', border: 'border-indigo-500/30', text: 'text-indigo-400' },
};

// Real Chief of Staff jobs from Greenhouse API - December 2024
export const chiefOfStaffJobs: ChiefOfStaffJob[] = [
  // Tech / AI Jobs
  {
    id: "nuro-ai-platform",
    title: "Chief of Staff, AI Platform",
    company: "Nuro",
    heroImage: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400&q=75&fm=webp",
    heroImageAlt: "Autonomous vehicle technology",
    location: "Mountain View, California",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "$160,000 - $240,000",
    description: "Join Nuro, the leader in autonomous delivery vehicles, as Chief of Staff to the AI Platform team. Drive strategic initiatives and cross-functional collaboration for our AI/ML platform.",
    skills: ["Strategic Planning", "Technical Program Management", "Cross-Functional Collaboration", "Analytical Judgment"],
    postedDate: "2024-12-20",
    externalUrl: "https://nuro.ai/careersitem?gh_jid=7235577",
    source: "greenhouse",
    category: "tech",
    executiveType: "Division Head",
    companyStage: "Series C+",
  },
  {
    id: "nuro-hardware",
    title: "Chief of Staff, Vehicle Platform & Hardware",
    company: "Nuro",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=75&fm=webp",
    heroImageAlt: "Robotics and hardware engineering",
    location: "Mountain View, California",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "$176,400 - $264,600",
    description: "Lead strategic operations for Nuro's Vehicle Platform & Hardware division. Partner with engineering leadership to drive program execution and team effectiveness.",
    skills: ["Strategic Operations", "Analytical Skills", "Project Management", "Technical Acumen"],
    postedDate: "2024-12-18",
    externalUrl: "https://nuro.ai/careersitem?gh_jid=7378154",
    source: "greenhouse",
    category: "tech",
    executiveType: "Division Head",
    companyStage: "Series C+",
  },
  {
    id: "scale-ai",
    title: "Chief of Staff",
    company: "Scale AI",
    heroImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&q=75&fm=webp",
    heroImageAlt: "AI and machine learning technology",
    location: "San Francisco, California",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "$180,600 - $225,750",
    description: "Scale AI is accelerating AI development. As Chief of Staff, you'll work directly with leadership to drive company-wide strategic initiatives and operational excellence.",
    skills: ["Management Consulting", "Finance", "High-Growth Technology", "Marketplace Business"],
    postedDate: "2024-12-15",
    externalUrl: "https://job-boards.greenhouse.io/scaleai/jobs/4642756005",
    source: "greenhouse",
    category: "tech",
    executiveType: "CEO",
    companyStage: "Growth",
  },
  {
    id: "addepar-rd",
    title: "Chief of Staff - R&D",
    company: "Addepar",
    heroImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&q=75&fm=webp",
    heroImageAlt: "Financial technology platform",
    location: "United States (Remote)",
    country: "United States",
    workMode: "Remote",
    type: "Full-time",
    salary: "$143,000 - $224,000",
    description: "Addepar is the financial technology platform for wealth management. Join as Chief of Staff to R&D, driving strategic initiatives and operational excellence across engineering.",
    skills: ["Strategic Thinking", "Technical Fluency", "Operational Follow-Through", "Communication"],
    postedDate: "2024-12-22",
    externalUrl: "https://job-boards.greenhouse.io/addepar1/jobs/8120254002",
    source: "greenhouse",
    category: "tech",
    executiveType: "Division Head",
    companyStage: "Growth",
  },
  {
    id: "dataiku",
    title: "Chief of Staff to CEO",
    company: "Dataiku",
    heroImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=75&fm=webp",
    heroImageAlt: "Data analytics platform",
    location: "New York, New York",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "$180,000 - $220,000",
    description: "Dataiku is the platform for Everyday AI. As Chief of Staff to the CEO, you'll drive strategic initiatives, board preparation, and cross-functional alignment.",
    skills: ["Strategy", "Board Management", "Cross-Functional Leadership", "Analytics"],
    postedDate: "2024-12-19",
    externalUrl: "https://job-boards.greenhouse.io/dataikiujobs/jobs/7718718002",
    source: "greenhouse",
    category: "tech",
    executiveType: "CEO",
    companyStage: "Series C+",
  },
  // Finance Jobs
  {
    id: "mongodb-cfo",
    title: "Chief of Staff to the CFO",
    company: "MongoDB",
    heroImage: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400&q=75&fm=webp",
    heroImageAlt: "MongoDB database technology company",
    location: "Austin, Texas",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "$129,000 - $253,000",
    description: "MongoDB is the leading modern database platform. As Chief of Staff to the CFO, you'll drive strategic finance initiatives, manage key projects, and support executive decision-making.",
    skills: ["Program Management", "Analytical Thinking", "Communication", "Organizational Skills"],
    postedDate: "2024-12-17",
    externalUrl: "https://www.mongodb.com/careers/job/?gh_jid=7380013",
    source: "greenhouse",
    category: "finance",
    executiveType: "CFO",
    companyStage: "Public",
  },
  // Healthcare Jobs
  {
    id: "iterative-health",
    title: "Chief of Staff to COO",
    company: "Iterative Health",
    heroImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=75&fm=webp",
    heroImageAlt: "Healthcare AI technology",
    location: "Cambridge, Massachusetts",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "$190,000 - $250,000",
    description: "Iterative Health uses AI to transform gastroenterology care. As Chief of Staff to the COO, you'll lead strategic operations, drive cross-functional initiatives, and support company scaling.",
    skills: ["Management Consulting", "Operations", "Strategy", "Program Management"],
    postedDate: "2024-12-16",
    externalUrl: "https://job-boards.greenhouse.io/iterativehealth/jobs/4627574006",
    source: "greenhouse",
    category: "healthcare",
    executiveType: "COO",
    companyStage: "Series B",
  },
  {
    id: "lantern",
    title: "Chief of Staff",
    company: "Lantern",
    heroImage: "https://images.unsplash.com/photo-1559028012-481c04fa702d?w=400&q=75&fm=webp",
    heroImageAlt: "Mental health technology",
    location: "San Francisco, California",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "$150,000 - $180,000",
    description: "Lantern is transforming specialty care navigation. As Chief of Staff, you'll work closely with the CEO to drive strategic initiatives and company-wide operations.",
    skills: ["Strategy", "Operations", "Healthcare", "Cross-Functional Leadership"],
    postedDate: "2024-12-20",
    externalUrl: "https://job-boards.greenhouse.io/lantern/jobs/7741854002",
    source: "greenhouse",
    category: "healthcare",
    executiveType: "CEO",
    companyStage: "Series B",
  },
  // Enterprise Jobs
  {
    id: "simplisafe",
    title: "Chief of Staff to the President",
    company: "SimpliSafe",
    heroImage: "https://images.unsplash.com/photo-1558002038-1055907df827?w=400&q=75&fm=webp",
    heroImageAlt: "Home security technology",
    location: "Boston, Massachusetts",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "$225,000 - $275,000",
    description: "SimpliSafe protects millions of homes. As Chief of Staff to the President, you'll drive GTM strategy, lead cross-functional initiatives, and support executive decision-making.",
    skills: ["GTM Strategy", "Management Consulting", "Product Strategy", "CX Leadership"],
    postedDate: "2024-12-14",
    externalUrl: "https://job-boards.greenhouse.io/simplisafe/jobs/7440434",
    source: "greenhouse",
    category: "enterprise",
    executiveType: "President",
    companyStage: "Growth",
  },
  {
    id: "compass",
    title: "Chief of Staff",
    company: "Compass",
    heroImage: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&q=75&fm=webp",
    heroImageAlt: "Real estate technology platform",
    location: "New York, New York",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "$175,000 - $225,000",
    description: "Compass is the largest independent real estate brokerage. As Chief of Staff, you'll partner with executive leadership to drive strategic initiatives and operational excellence.",
    skills: ["Strategy", "Operations", "Real Estate", "Cross-Functional Leadership"],
    postedDate: "2024-12-18",
    externalUrl: "https://job-boards.greenhouse.io/compass/jobs/7741267002",
    source: "greenhouse",
    category: "enterprise",
    executiveType: "CEO",
    companyStage: "Public",
  },
  // Startup Jobs
  {
    id: "shopmy",
    title: "Chief of Staff to the COO",
    company: "ShopMy",
    heroImage: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&q=75&fm=webp",
    heroImageAlt: "E-commerce and creator platform",
    location: "New York, New York",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "$140,000 - $150,000",
    description: "ShopMy is the leading creator commerce platform. As Chief of Staff to the COO, you'll drive operations, strategy, and cross-functional initiatives in a fast-paced startup.",
    skills: ["Management Consulting", "Business Operations", "Strategy", "Product Management"],
    postedDate: "2024-12-21",
    externalUrl: "https://job-boards.greenhouse.io/shopmy/jobs/5040854008",
    source: "greenhouse",
    category: "startup",
    executiveType: "COO",
    companyStage: "Series B",
  },
  {
    id: "xendit",
    title: "Chief of Staff - LATAM",
    company: "Xendit",
    heroImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&q=75&fm=webp",
    heroImageAlt: "Fintech payment infrastructure",
    location: "Mexico City, Mexico",
    country: "Mexico",
    workMode: "On-site",
    type: "Full-time",
    salary: "Competitive + Equity",
    description: "Xendit provides payment infrastructure across Southeast Asia. As Chief of Staff for LATAM expansion, you'll work with the GM to launch Xendit in Latin America.",
    skills: ["Strategy", "Operations", "Project Management", "Communication"],
    postedDate: "2024-12-24",
    externalUrl: "https://www.xendit.co/en/careers/job-application/?gh_jid=7562315003",
    source: "greenhouse",
    category: "startup",
    executiveType: "Founder",
    companyStage: "Series C+",
  },
  {
    id: "babylist",
    title: "Chief of Staff",
    company: "Babylist",
    heroImage: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&q=75&fm=webp",
    heroImageAlt: "Baby registry and commerce platform",
    location: "San Francisco, California",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "$160,000 - $200,000",
    description: "Babylist is the leading baby registry platform. As Chief of Staff, you'll partner with executive leadership to drive company strategy and cross-functional initiatives.",
    skills: ["Strategy", "E-commerce", "Operations", "Cross-Functional Leadership"],
    postedDate: "2024-12-19",
    externalUrl: "https://job-boards.greenhouse.io/babylist/jobs/7741856002",
    source: "greenhouse",
    category: "startup",
    executiveType: "CEO",
    companyStage: "Growth",
  },
  // Nonprofit / Mission-Driven
  {
    id: "zipline",
    title: "Chief of Staff",
    company: "Zipline",
    heroImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&q=75&fm=webp",
    heroImageAlt: "Drone delivery for healthcare",
    location: "Kigali, Rwanda",
    country: "Rwanda",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "Competitive",
    description: "Zipline designs, manufactures, and operates the world's largest drone delivery network. As Chief of Staff, you'll support strategic initiatives in our mission to provide instant logistics.",
    skills: ["Program Management", "Project Management", "Partnerships", "Stakeholder Management"],
    postedDate: "2024-12-15",
    externalUrl: "https://www.flyzipline.com/careers/open-roles?gh_jid=7337300003",
    source: "greenhouse",
    category: "nonprofit",
    executiveType: "CEO",
    companyStage: "Series C+",
  },
  {
    id: "instiglio",
    title: "Associate/Senior Associate Chief of Staff",
    company: "Instiglio",
    heroImage: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&q=75&fm=webp",
    heroImageAlt: "Global development consulting",
    location: "Remote (Global)",
    country: "Global",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "Competitive",
    description: "Instiglio is a mission-driven organization working with governments and NGOs. As Chief of Staff, you'll drive strategic initiatives, change management, and AI integration.",
    skills: ["Strategic Leadership", "Change Management", "AI Integration", "Project Management"],
    postedDate: "2024-12-20",
    externalUrl: "https://job-boards.greenhouse.io/instiglio/jobs/5742477004",
    source: "greenhouse",
    category: "nonprofit",
    executiveType: "CEO",
    companyStage: "Growth",
  },
  // Consulting
  {
    id: "human-agency",
    title: "Chief of Staff",
    company: "Human Agency",
    heroImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&q=75&fm=webp",
    heroImageAlt: "Consulting and strategy firm",
    location: "Toronto, Ontario",
    country: "Canada",
    workMode: "Remote",
    type: "Full-time",
    salary: "Competitive",
    description: "Human Agency is a strategic consulting firm. As Chief of Staff, you'll support operations, client services, and strategic initiatives in a fast-paced consulting environment.",
    skills: ["Operations", "Client Services", "Project Management", "AI Fluency"],
    postedDate: "2024-12-22",
    externalUrl: "https://job-boards.greenhouse.io/humanagency/jobs/7571668003",
    source: "greenhouse",
    category: "consulting",
    executiveType: "Managing Partner",
    companyStage: "Growth",
  },
  {
    id: "wave",
    title: "Chief of Staff",
    company: "Wave",
    heroImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&q=75&fm=webp",
    heroImageAlt: "Mobile money and fintech",
    location: "Remote (Africa-focused)",
    country: "Global",
    workMode: "Remote",
    type: "Full-time",
    salary: "Competitive",
    description: "Wave is building mobile money infrastructure for Africa. As Chief of Staff, you'll drive strategic projects and cross-functional collaboration in our mission to provide financial access.",
    skills: ["Project Management", "Communication", "Collaboration", "Interpersonal Skills"],
    postedDate: "2024-12-18",
    externalUrl: "https://www.wave.com/en/careers/job/5661509004?gh_jid=5661509004",
    source: "greenhouse",
    category: "startup",
    executiveType: "CEO",
    companyStage: "Series C+",
  },
  // Additional jobs from career sites
  {
    id: "equinix",
    title: "Chief of Staff, Digital GTM & Digital Operations",
    company: "Equinix",
    heroImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&q=75&fm=webp",
    heroImageAlt: "Data center infrastructure",
    location: "Toronto, Ontario",
    country: "Canada",
    workMode: "On-site",
    type: "Full-time",
    salary: "$177,000 - $265,000 CAD",
    description: "Equinix is the world's digital infrastructure company. As Chief of Staff for Digital GTM & Operations, you'll drive strategic initiatives and operational excellence across our digital business.",
    skills: ["Digital Strategy", "GTM Operations", "Cross-Functional Leadership", "Analytics"],
    postedDate: "2024-12-28",
    externalUrl: "https://equinix.wd1.myworkdayjobs.com/External/job/Dallas-Infomart-Office-DAI/Chief-of-Staff--Digital-GTM---Digital-Operations_JR-156370",
    source: "company-site",
    category: "enterprise",
    executiveType: "Division Head",
    companyStage: "Public",
  },
  {
    id: "david-energy",
    title: "Chief of Staff",
    company: "David Energy",
    heroImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=400&q=75&fm=webp",
    heroImageAlt: "Clean energy technology",
    location: "New York, New York",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "$170,000 - $190,000",
    description: "David Energy is building the operating system for the clean energy transition. As Chief of Staff, you'll partner with leadership to drive company strategy and operations.",
    skills: ["Energy Industry", "Strategy", "Operations", "Cross-Functional Leadership"],
    postedDate: "2024-12-28",
    externalUrl: "https://jobs.ashbyhq.com/davidenergy/d7383577-462c-44db-9d8e-c88f412be927",
    source: "company-site",
    category: "startup",
    executiveType: "CEO",
    companyStage: "Series B",
  },
  {
    id: "northrop-grumman",
    title: "Chief of Staff",
    company: "Northrop Grumman",
    heroImage: "https://images.unsplash.com/photo-1517976547714-720226b864c1?w=400&q=75&fm=webp",
    heroImageAlt: "Aerospace and defense technology",
    location: "London, United Kingdom",
    country: "United Kingdom",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "£70,000 - £80,000",
    description: "Northrop Grumman is a leading global aerospace and defense company. As Chief of Staff in our UK operations, you'll support executive leadership and drive strategic initiatives.",
    skills: ["Defense Industry", "Strategy", "Stakeholder Management", "Executive Support"],
    postedDate: "2024-12-28",
    externalUrl: "https://ngc.wd1.myworkdayjobs.com/Northrop_Grumman_External_Site/job/United-Kingdom-London/Chief-of-Staff_R10217750",
    source: "company-site",
    category: "enterprise",
    executiveType: "Division Head",
    companyStage: "Public",
  },
  {
    id: "early-warning",
    title: "Sr. Director, Partnership Operations & Chief of Staff",
    company: "Early Warning (Zelle)",
    heroImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&q=75&fm=webp",
    heroImageAlt: "Financial technology payments",
    location: "Scottsdale, Arizona",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "$188,000 - $282,000",
    description: "Early Warning operates Zelle, the leading P2P payments network. As Chief of Staff for Partnership Operations, you'll drive strategic initiatives across our financial institution partnerships.",
    skills: ["Payments Industry", "Partnership Management", "Strategy", "Operations"],
    postedDate: "2024-12-28",
    externalUrl: "https://earlywarning.wd5.myworkdayjobs.com/earlywarningcareers/job/New-York-City/Sr-Director--Partnership-Operations---Chief-of-Staff_REQ20251084",
    source: "company-site",
    category: "finance",
    executiveType: "Division Head",
    companyStage: "Enterprise",
  },
  {
    id: "handshake",
    title: "Chief of Staff, President & COO",
    company: "Handshake",
    heroImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&q=75&fm=webp",
    heroImageAlt: "Career platform for students",
    location: "San Francisco, California",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "Competitive + Equity",
    description: "Handshake is the #1 career network for students and recent grads. As Chief of Staff to the President & COO, you'll drive strategic initiatives and operational excellence.",
    skills: ["Strategy", "Operations", "EdTech", "Cross-Functional Leadership"],
    postedDate: "2024-12-28",
    externalUrl: "https://jobs.ashbyhq.com/handshake/71b4d520-4778-4f06-a006-38c62dc1e8bc",
    source: "company-site",
    category: "tech",
    executiveType: "President",
    companyStage: "Series C+",
  },
  {
    id: "outreach",
    title: "Chief of Staff, Office of the CEO",
    company: "Outreach",
    heroImage: "https://images.unsplash.com/photo-1552581234-26160f608093?w=400&q=75&fm=webp",
    heroImageAlt: "Sales engagement platform",
    location: "San Francisco, California",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "$150,000 - $220,000",
    description: "Outreach is the leading sales engagement platform. As Chief of Staff to the CEO, you'll drive company-wide strategic initiatives and support executive decision-making.",
    skills: ["SaaS", "Strategy", "Executive Support", "Cross-Functional Leadership"],
    postedDate: "2024-12-28",
    externalUrl: "https://jobs.lever.co/outreach/087c8a12-5d88-460a-9088-4ca7ba066f80",
    source: "company-site",
    category: "tech",
    executiveType: "CEO",
    companyStage: "Growth",
  },
  {
    id: "coca-cola",
    title: "Senior Director II, Innovation and Chief of Staff",
    company: "The Coca-Cola Company",
    heroImage: "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=400&q=75&fm=webp",
    heroImageAlt: "Coca-Cola global beverage company",
    location: "Atlanta, Georgia",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "$211,000 - $238,400",
    description: "The Coca-Cola Company is the world's largest beverage company. As Chief of Staff for Innovation, you'll drive strategic initiatives and operational excellence for our innovation portfolio.",
    skills: ["Innovation", "CPG Industry", "Strategy", "Cross-Functional Leadership"],
    postedDate: "2024-12-28",
    externalUrl: "https://coke.wd1.myworkdayjobs.com/Coca_Cola_Bottler_Careers/job/US---GA---Atlanta/Senior-Director-II--Innovation-and-Chief-of-Staff_R-132027-2",
    source: "company-site",
    category: "enterprise",
    executiveType: "Division Head",
    companyStage: "Public",
  },
  {
    id: "guidewire",
    title: "Chief of Staff",
    company: "Guidewire Software",
    heroImage: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&q=75&fm=webp",
    heroImageAlt: "Insurance software platform",
    location: "Remote (United States)",
    country: "United States",
    workMode: "Remote",
    type: "Full-time",
    salary: "$141,000 - $211,000",
    description: "Guidewire is the platform P&C insurers trust. As Chief of Staff, you'll drive strategic initiatives and business operations across the organization.",
    skills: ["InsurTech", "Strategy", "Business Operations", "Program Management"],
    postedDate: "2024-12-28",
    externalUrl: "https://wd5.myworkdaysite.com/recruiting/guidewire/external/job/Remote-USA/Business-Operations-Project-Manager_JR_13968",
    source: "company-site",
    category: "tech",
    executiveType: "CEO",
    companyStage: "Public",
  },
  {
    id: "altais",
    title: "Chief of Staff to CEO",
    company: "Altais",
    heroImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=75&fm=webp",
    heroImageAlt: "Healthcare technology platform",
    location: "California (Hybrid)",
    country: "United States",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "$150,000 - $200,000",
    description: "Altais is transforming healthcare delivery. As Chief of Staff to the CEO, you'll drive strategic initiatives, board preparation, and cross-functional alignment.",
    skills: ["Healthcare", "Strategy", "Executive Support", "Board Management"],
    postedDate: "2024-12-28",
    externalUrl: "https://altaishealthsolutions.wd108.myworkdayjobs.com/External/job/Hybrid---CA/Chief-of-Staff-to-CEO_",
    source: "company-site",
    category: "healthcare",
    executiveType: "CEO",
    companyStage: "Growth",
  },
  {
    id: "blue-orange",
    title: "Chief of Staff",
    company: "Blue Orange Digital",
    heroImage: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=400&q=75&fm=webp",
    heroImageAlt: "Data and AI consulting",
    location: "New York, New York",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "$150,000 - $180,000",
    description: "Blue Orange Digital is a leading data and AI consultancy. As Chief of Staff, you'll drive strategic initiatives, operations, and cross-functional alignment.",
    skills: ["Consulting", "Data/AI", "Strategy", "Operations"],
    postedDate: "2024-12-28",
    externalUrl: "https://careers.blueorange.digital/jobs/517825-chief-of-staff",
    source: "company-site",
    category: "consulting",
    executiveType: "CEO",
    companyStage: "Growth",
  },
  {
    id: "barclays",
    title: "Strategy and Governance Chief of Staff - Director",
    company: "Barclays",
    heroImage: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=400&q=75&fm=webp",
    heroImageAlt: "Global investment bank",
    location: "Whippany, New Jersey",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "Competitive",
    description: "Barclays is a British multinational investment bank. As Chief of Staff for Strategy and Governance, you'll drive strategic initiatives and governance across the organization.",
    skills: ["Investment Banking", "Strategy", "Governance", "Stakeholder Management"],
    postedDate: "2024-12-28",
    externalUrl: "https://barclays.wd3.myworkdayjobs.com/External_Career_Site_Barclays/job/Building-400-115-South-Jefferson-Rd-Campus-Whippany/Strategy-and-Governance-Chief-of-Staff---Director_JR-0000081568",
    source: "company-site",
    category: "finance",
    executiveType: "Division Head",
    companyStage: "Public",
  },
  {
    id: "paradox",
    title: "Chief Of Staff to Startup CEO - EdTech",
    company: "Paradox",
    heroImage: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&q=75&fm=webp",
    heroImageAlt: "EdTech startup",
    location: "Dubai, UAE (Remote)",
    country: "United Arab Emirates",
    workMode: "Remote",
    type: "Full-time",
    salary: "Competitive + Equity",
    description: "Paradox is an EdTech startup transforming education. As Chief of Staff to the CEO, you'll drive strategic initiatives, fundraising support, and company operations.",
    skills: ["EdTech", "Startup Operations", "Strategy", "Fundraising"],
    postedDate: "2024-12-28",
    externalUrl: "https://jobs.ashbyhq.com/paradox/5b610ac3-4f92-4b29-9f50-5a0f38b41dc0",
    source: "company-site",
    category: "startup",
    executiveType: "CEO",
    companyStage: "Seed",
  },
  {
    id: "uscreen",
    title: "Chief of Staff",
    company: "Uscreen",
    heroImage: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=400&q=75&fm=webp",
    heroImageAlt: "Video streaming platform",
    location: "Remote (United States)",
    country: "United States",
    workMode: "Remote",
    type: "Full-time",
    salary: "Competitive",
    description: "Uscreen is the all-in-one video monetization platform. As Chief of Staff, you'll drive strategic initiatives and operations across the organization.",
    skills: ["Video/Streaming", "Strategy", "Operations", "Cross-Functional Leadership"],
    postedDate: "2024-12-28",
    externalUrl: "https://uscreen.bamboohr.com/careers/151",
    source: "company-site",
    category: "tech",
    executiveType: "CEO",
    companyStage: "Growth",
  },
  // LinkedIn Jobs
  {
    id: "mondrian-alpha",
    title: "Global Chief of Staff (CIO Office) – Major Hedge Fund",
    company: "Mondrian Alpha",
    heroImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400&q=75&fm=webp",
    heroImageAlt: "Hedge fund trading floor",
    location: "New York, New York",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "Competitive + Bonus",
    description: "Join a major hedge fund as Global Chief of Staff in the CIO Office. You'll drive strategic initiatives, coordinate across investment teams, and support the Chief Investment Officer.",
    skills: ["Hedge Fund", "Investment Management", "Strategy", "CIO Support"],
    postedDate: "2024-12-29",
    externalUrl: "https://www.linkedin.com/jobs/view/global-chief-of-staff-cio-office-%E2%80%93-major-hedge-fund-at-mondrian-alpha-4350850350",
    source: "linkedin",
    category: "finance",
    executiveType: "Division Head",
    companyStage: "Enterprise",
  },
  {
    id: "pflegia",
    title: "Chief of Staff to CEO",
    company: "Pflegia",
    heroImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&q=75&fm=webp",
    heroImageAlt: "Healthcare technology startup",
    location: "Berlin, Germany",
    country: "Germany",
    workMode: "On-site",
    type: "Full-time",
    salary: "Competitive + Equity",
    description: "Pflegia is transforming healthcare staffing in Germany. As Chief of Staff to the CEO, you'll drive strategic initiatives, company operations, and growth in the European market.",
    skills: ["Healthcare", "Startup Operations", "Strategy", "European Markets"],
    postedDate: "2024-12-29",
    externalUrl: "https://de.linkedin.com/jobs/view/chief-of-staff-to-ceo-berlin-m-w-d-at-pflegia-4350700487",
    source: "linkedin",
    category: "healthcare",
    executiveType: "CEO",
    companyStage: "Series B",
  },
  {
    id: "lavela-health",
    title: "Chief of Staff",
    company: "Lavela Health",
    heroImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=75&fm=webp",
    heroImageAlt: "Digital health platform",
    location: "Remote (United States)",
    country: "United States",
    workMode: "Remote",
    type: "Full-time",
    salary: "Competitive",
    description: "Lavela Health is a digital health company focused on women's health. As Chief of Staff, you'll drive strategic planning, organizational leadership, and cross-functional initiatives.",
    skills: ["Strategic Planning", "Organizational Leadership", "Project Management", "Healthcare"],
    postedDate: "2024-12-29",
    externalUrl: "https://www.linkedin.com/jobs/view/chief-of-staff-at-lavela-health-4344133551",
    source: "linkedin",
    category: "healthcare",
    executiveType: "CEO",
    companyStage: "Seed",
  },
  {
    id: "nulixir",
    title: "Chief of Staff",
    company: "Nulixir Inc.",
    heroImage: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=400&q=75&fm=webp",
    heroImageAlt: "Biotech laboratory",
    location: "Austin, Texas",
    country: "United States",
    workMode: "On-site",
    type: "Full-time",
    salary: "Competitive + Equity",
    description: "Nulixir is pioneering nanotechnology for drug delivery. As Chief of Staff, you'll support the CEO with strategy, analytics, and cross-functional initiatives in a fast-paced biotech environment.",
    skills: ["Management Consulting", "Strategy", "Analytics", "Biotech"],
    postedDate: "2024-12-29",
    externalUrl: "https://www.linkedin.com/jobs/view/chief-of-staff-at-nulixir-inc-4329476090",
    source: "linkedin",
    category: "startup",
    executiveType: "CEO",
    companyStage: "Seed",
  },
  {
    id: "canvvs",
    title: "Chief of Staff",
    company: "CANVVS",
    heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&q=75&fm=webp",
    heroImageAlt: "Creative agency office",
    location: "Leeds, United Kingdom",
    country: "United Kingdom",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "Competitive",
    description: "CANVVS is a creative agency. As Chief of Staff, you'll drive talent acquisition, people operations, and general management across the organization.",
    skills: ["Talent Acquisition", "People Operations", "General Management", "Creative Industry"],
    postedDate: "2024-12-29",
    externalUrl: "https://uk.linkedin.com/jobs/view/chief-of-staff-at-canvvs-4346551996",
    source: "linkedin",
    category: "consulting",
    executiveType: "CEO",
    companyStage: "Growth",
  },
  {
    id: "rowen-wren",
    title: "Chief of Staff",
    company: "Rowen & Wren",
    heroImage: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=75&fm=webp",
    heroImageAlt: "Home interiors retail",
    location: "Woking, United Kingdom",
    country: "United Kingdom",
    workMode: "Hybrid",
    type: "Full-time",
    salary: "Competitive",
    description: "Rowen & Wren is a premium home interiors brand. As Chief of Staff, you'll drive operations management, business strategy, and leadership initiatives.",
    skills: ["Operations Management", "Business Management", "Leadership", "Retail"],
    postedDate: "2024-12-29",
    externalUrl: "https://uk.linkedin.com/jobs/view/chief-of-staff-at-rowen-wren-4350597490",
    source: "linkedin",
    category: "enterprise",
    executiveType: "CEO",
    companyStage: "Growth",
  },
];

// Get unique categories from jobs
export const getCategories = (): JobCategory[] => {
  const categories = new Set(chiefOfStaffJobs.map(job => job.category));
  return Array.from(categories);
};

// Get jobs by category
export const getJobsByCategory = (category: JobCategory): ChiefOfStaffJob[] => {
  return chiefOfStaffJobs.filter(job => job.category === category);
};

// Get job count by category
export const getJobCountByCategory = (): Record<JobCategory, number> => {
  const counts = {} as Record<JobCategory, number>;
  chiefOfStaffJobs.forEach(job => {
    counts[job.category] = (counts[job.category] || 0) + 1;
  });
  return counts;
};
